name: Android CI

on:
  push:
    branches: [ master ]
    tags-ignore:
      - '*'
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: Detekt check
        run: bash ./gradlew detekt --stacktrace
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
